#!/bin/bash
# Show files ready to transfer to cluster

echo "================================================================================"
echo "FILES READY FOR CLUSTER TRANSFER"
echo "================================================================================"
echo ""

echo "📁 Tensor-type mapping files:"
echo "   Location: outputs/tensor_types/"
echo ""
ls -lh outputs/tensor_types/*.txt 2>/dev/null || echo "   ❌ No tensor-type files found!"
echo ""

echo "📁 Quantization script:"
echo "   Location: scripts/14b_create_mixed_gguf_cluster.sh"
echo ""
ls -lh scripts/14b_create_mixed_gguf_cluster.sh 2>/dev/null || echo "   ❌ Script not found!"
echo ""

echo "================================================================================"
echo "INSTRUCTIONS"
echo "================================================================================"
echo ""
echo "See CLUSTER_QUANTIZATION_STEPS.md for detailed transfer instructions."
echo ""
echo "Quick transfer (if kubectl is available):"
echo ""
echo "  # Create directory on cluster"
echo "  kubectl exec mixtral-dev -n user-sbowerma -- mkdir -p /workspace/outputs/tensor_types"
echo ""
echo "  # Copy tensor-type files"
echo "  cd outputs/tensor_types"
echo "  for f in *.txt; do"
echo "    kubectl cp \$f user-sbowerma/mixtral-dev:/workspace/outputs/tensor_types/"
echo "  done"
echo "  cd ../.."
echo ""
echo "  # Copy script"
echo "  kubectl cp scripts/14b_create_mixed_gguf_cluster.sh user-sbowerma/mixtral-dev:/workspace/create_mixed_gguf.sh"
echo ""
echo "  # Run on cluster"
echo "  kubectl exec mixtral-dev -n user-sbowerma -- bash /workspace/create_mixed_gguf.sh"
echo ""
